#!/usr/bin/env bash
# pre-commit-markdownlint.sh
# Generated by autoharness | Template: pre-commit-markdownlint.sh.tmpl
#
# Pre-commit hook: runs markdownlint on staged .md files.
# Exit code 1 on violations; 0 when all files pass.
#
# Install: copy to .git/hooks/pre-commit (or register via .pre-commit-config.yaml)

set -uo pipefail

# Run from repo root so repo-root-relative paths from git are valid.
# Resolve fail-closed: without `set -e`, a failing `git rev-parse` would
# otherwise leave the hook running in an unknown directory, produce an empty
# file list, and exit 0 without linting anything — a silent pass.
REPO_ROOT="$(git rev-parse --show-toplevel)" || {
  echo "ERROR: not inside a git repository — refusing to run markdownlint hook." >&2
  exit 1
}
if [ -z "$REPO_ROOT" ] || ! cd "$REPO_ROOT"; then
  echo "ERROR: could not change to repository root '$REPO_ROOT'." >&2
  exit 1
fi

# Collect staged .md files using NUL delimiters (handles spaces in paths)
STAGED_MD_FILES=()
while IFS= read -r -d '' f; do
  STAGED_MD_FILES+=("$f")
done < <(git diff --cached --name-only -z --diff-filter=ACMR -- '*.md')

if [ ${#STAGED_MD_FILES[@]} -eq 0 ]; then
  exit 0
fi

# Verify markdownlint-cli is available
if ! command -v markdownlint &>/dev/null; then
  echo "WARNING: markdownlint-cli not found — skipping Markdown lint check." >&2
  echo "Install with: npm install -g markdownlint-cli" >&2
  exit 0
fi

echo "Running markdownlint on staged Markdown files..."
markdownlint "${STAGED_MD_FILES[@]}" || {
  echo "ERROR: markdownlint violations detected (P-008). Fix heading hierarchy issues before committing." >&2
  exit 1
}

exit 0
